package com.ssm.model;

public class User {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column USER.ID
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column USER.USERNAME
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	private String username;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column USER.USERAGE
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	private Integer userage;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column USER.USERADDRESS
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	private String useraddress;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column USER.ID
	 *
	 * @return the value of USER.ID
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column USER.ID
	 *
	 * @param id the value for USER.ID
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column USER.USERNAME
	 *
	 * @return the value of USER.USERNAME
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column USER.USERNAME
	 *
	 * @param username the value for USER.USERNAME
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column USER.USERAGE
	 *
	 * @return the value of USER.USERAGE
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	public Integer getUserage() {
		return userage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column USER.USERAGE
	 *
	 * @param userage the value for USER.USERAGE
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	public void setUserage(Integer userage) {
		this.userage = userage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column USER.USERADDRESS
	 *
	 * @return the value of USER.USERADDRESS
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	public String getUseraddress() {
		return useraddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column USER.USERADDRESS
	 *
	 * @param useraddress the value for USER.USERADDRESS
	 *
	 * @mbg.generated Wed Jul 22 12:31:26 CST 2020
	 */
	public void setUseraddress(String useraddress) {
		this.useraddress = useraddress == null ? null : useraddress.trim();
	}
}